apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: quay.io/dystewar/fio-openshift-storage-performance:latest
          imagePullPolicy: IfNotPresent
          name: kubestr-fio-benchmark
          workingDir: /target
          command:
            - /scripts/run-benchmark.sh
          volumeMounts:
            - mountPath: /target
              name: target
            - mountPath: /scripts
              name: kubestr-scripts
            - mountPath: /fio-jobs
              name: fio-jobs
        - image: docker.io/minio/mc
          imagePullPolicy: IfNotPresent
          name: mc-results-to-bucket
          workingDir: /target
          command: 
            - /mc/mc-results-to-bucket.sh
          envFrom:
            - configMapRef:
                name: storage-benchmark-results
            - secretRef:
                name: storage-benchmark-results
          volumeMounts:
            - mountPath: /target
              name: target
            - mountPath: /mc
              name: mc-results-to-bucket 
      volumes:
        - name: kubestr-scripts
          configMap:
            name: run-benchmark
            defaultMode: 0777
        - name: mc-results-to-bucket
          configMap: 
            name: mc-results-to-bucket
            defaultMode: 0777
        - name: fio-jobs
          configMap: 
            name: fio-jobs
