apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels: 
  app: fio-benchmark
resources:
    - fio-jobs.yaml

configMapGenerator:
  - name: benchmark-scripts
    files:
      - run-benchmark.sh
      - mc-results-to-bucket.sh
      - copy-results.sh
